[package]
name = "sample-rust-expr"
version = "0.1.0"
authors = ["NaotoSuzuki <suzuki.z2o.naoto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
